image: alpine/edge
packages:
  - go
sources:
  - https://git.sr.ht/~mariusor/storage-all
secrets:
  - 231516a2-ca5d-42d0-8da1-b1d300485344
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-all
      make test
  - coverage: |
      set -a +x
      cd storage-all
      make coverage
  - bench: |
      cd storage-all
      make bench
  - conformance-suite: |
      cd storage-all
      go test -tags conformance -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - conformance-suite-fs: |
      cd storage-all
      go test -tags 'conformance storage_fs' -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - conformance-suite-sqlite: |
      cd storage-all
      go test -tags 'conformance storage_sqlite' -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - conformance-suite-boltdb: |
      cd storage-all
      go test -tags 'conformance storage_boltdb' -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - conformance-suite-badger: |
      cd storage-all
      go test -tags 'conformance storage_badger' -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - coverage-upload: |
      cd storage-all
      git switch -C master origin/master
      make coverage
      go run github.com/mattn/goveralls@latest -flagname unit-tests -service=${CI_NAME} -coverprofile storage-all.coverprofile -repotokenfile ~/.coveralls.tok
