image: archlinux
packages:
  - go
  - podman
  - golangci-lint
sources:
  - https://git.sr.ht/~mariusor/storage-all
secrets:
  - 231516a2-ca5d-42d0-8da1-b1d300485344
environment:
  GO111MODULE: 'on'
  DOCKER_HOST: unix:///run/user/1000/podman/podman.sock
tasks:
  - fmt: |
      cd storage-all
      test -z $(gofmt -l .)
  - tests: |
      cd storage-all
      make test
  - coverage: |
      set -a +x
      cd storage-all
      make coverage
  - bench: |
      _user=$(id -un)

      echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf.d/unq-search.conf
      echo "${_user}:10000:65536" | sudo tee /etc/subuid
      echo "${_user}:10000:65536" | sudo tee /etc/subgid

      podman system migrate
      systemctl --user enable --now podman.service podman.socket

      cd storage-all
      make bench
  - conformance-suite: |
      cd storage-all
      go test -tags conformance -count=1 -json . | go tool gotestfmt -showteststatus
  - conformance-suite-fs: |
      cd storage-all
      go test -tags 'conformance storage_fs' -count=1 -json . | go tool gotestfmt -showteststatus
  - conformance-suite-sqlite: |
      cd storage-all
      go test -tags 'conformance storage_sqlite' -count=1 -json . | go tool gotestfmt -showteststatus
  - conformance-suite-boltdb: |
      cd storage-all
      go test -tags 'conformance storage_boltdb' -count=1 -json . | go tool gotestfmt -showteststatus
  - conformance-suite-badger: |
      cd storage-all
      go test -tags 'conformance storage_badger' -count=1 -json . | go tool gotestfmt -showteststatus
  - conformance-suite-postgres: |
      cd storage-all
      go test -tags 'conformance storage_postgres' -count=1 -json . | go tool gotestfmt -showteststatus
  - coverage-upload: |
      cd storage-all
      git switch -C master origin/master
      make coverage
      go tool goveralls -flagname unit-tests -service=${CI_NAME} -coverprofile storage-all.coverprofile -repotokenfile ~/.coveralls.tok
  - lint: |
      cd storage-all
      golangci-lint run || true
